services:
  app:
    container_name: tweetulator-app
    depends_on:
      - db
    image: node:16.13.2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:8080"
    env_file:
      - .env
      - .env.production
    environment:
      - MONGODB_USERNAME=$_MONGODB_USERNAME
      - MONGODB_PASSWORD=$_MONGODB_PASSWORD
      - MONGODB_HOSTNAME=$_MONGODB_HOSTNAME
      - MONGODB_PORT=$_MONGODB_PORT
      - MONGODB_DATABASE=$_MONGODB_DATABASE
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - tweetulator-network
  db:
    container_name: tweetulator-db
    image: mongo:5.0.5
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$_MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$_MONGODB_PASSWORD
    volumes:
      - db-data:/data/db
    networks:
      - tweetulator-network

volumes:
  node_modules:
    driver: local
  db-data:
    driver: local

networks:
  tweetulator-network:
    driver: bridge
