services:
  app-service:
    container_name: app-service
    image: node:16.13.2
    depends_on:
      - db-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - tweetulator-network
  db-service:
    container_name: db-service
    image: mongo:5.0.5
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - tweetulator-network

volumes:
  node_modules:
    driver: local
  db-data:
    driver: local

networks:
  tweetulator-network:
    driver: bridge
